/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.*;
import DTO.Course;
import DTO.OnlineCourse;
import DTO.OnsiteCourse;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ADMIN
 */
public class AddNewCourse1 extends javax.swing.JFrame {
    CourseForm cf = new CourseForm();
    CourseBLL couBLL = new CourseBLL();
    OnlineCourseBLL olcBLL = new OnlineCourseBLL();
    OnsiteCourseBLL oscBLL = new OnsiteCourseBLL();
    ArrayList<JPanel> checkBoxPanels;
    JSpinner hourSpinner;
    JSpinner minuteSpinner;
    /**
     * Creates new form AddNewCourse
     */
    public AddNewCourse1(CourseForm cft) {
        cf = cft;
        initComponents();
        generateDays();
        generateTime();
        textFieldChange();
        jpnOnlineCourse.setVisible(false);
        jpnOnsiteCourse.setVisible(false);
        setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE); // Khi đóng cửa sổ, chỉ đóng cửa sổ này, không kết thúc ứng dụng
        setLocationRelativeTo(null);
    }
    
    private void generateDays() {
        String [] daysOfWeek = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
        jpnDays.setLayout(new BoxLayout(jpnDays, BoxLayout.X_AXIS));
        checkBoxPanels = new ArrayList<>();
        for (String day : daysOfWeek) {
            JPanel checkBoxPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JCheckBox checkBox = new JCheckBox(day);
            checkBoxPanel.add(checkBox);
            checkBoxPanels.add(checkBoxPanel);
            jpnDays.add(checkBoxPanel);
        }
    }
    
        private void generateTime() {
        jpnTime.setLayout(new BoxLayout(jpnTime, BoxLayout.X_AXIS));
        SpinnerModel hourModel = new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerModel minuteModel = new SpinnerNumberModel(0, 0, 59, 1);

        hourSpinner = new JSpinner(hourModel);
        minuteSpinner = new JSpinner(minuteModel);

        JLabel hourLabel = new JLabel("Hour: ");
        JLabel minuteLabel = new JLabel("Minute: ");
        
        jpnTime.add(hourLabel);
        jpnTime.add(hourSpinner);
        jpnTime.add(minuteLabel);
        jpnTime.add(minuteSpinner);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnThem1 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jpnSearch = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfCourseId = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jspCredits = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfTitle = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jcbOnlineOnsite = new javax.swing.JComboBox<>();
        jbtnBack = new javax.swing.JButton();
        jbtnThem = new javax.swing.JButton();
        jbtnThem2 = new javax.swing.JButton();
        jpnOnlineCourse = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtfUrl = new javax.swing.JTextField();
        jpnOnsiteCourse = new javax.swing.JPanel();
        jpnTime = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpnDays = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpnLocation1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jtfLocation = new javax.swing.JTextField();

        jbtnThem1.setText("Thêm");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpnSearch.setMinimumSize(new java.awt.Dimension(0, 0));
        jpnSearch.setPreferredSize(new java.awt.Dimension(707, 250));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã khóa học:");

        jtfCourseId.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Số tín chỉ:");

        jspCredits.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jspCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jspCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tên khóa học:");

        jtfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTitleActionPerformed(evt);
            }
        });

        jPanel8.setPreferredSize(new java.awt.Dimension(317, 38));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Loại khóa học:");

        jcbOnlineOnsite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Online", "Onsite" }));
        jcbOnlineOnsite.setPreferredSize(new java.awt.Dimension(64, 22));
        jcbOnlineOnsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOnlineOnsiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbOnlineOnsite, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbOnlineOnsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jbtnBack.setText("Trở về");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnThem2.setText("Sửa");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("url:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnOnlineCourseLayout = new javax.swing.GroupLayout(jpnOnlineCourse);
        jpnOnlineCourse.setLayout(jpnOnlineCourseLayout);
        jpnOnlineCourseLayout.setHorizontalGroup(
            jpnOnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOnlineCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnOnlineCourseLayout.setVerticalGroup(
            jpnOnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOnlineCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Time:");

        javax.swing.GroupLayout jpnTimeLayout = new javax.swing.GroupLayout(jpnTime);
        jpnTime.setLayout(jpnTimeLayout);
        jpnTimeLayout.setHorizontalGroup(
            jpnTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jpnTimeLayout.setVerticalGroup(
            jpnTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Days:");

        javax.swing.GroupLayout jpnDaysLayout = new javax.swing.GroupLayout(jpnDays);
        jpnDays.setLayout(jpnDaysLayout);
        jpnDaysLayout.setHorizontalGroup(
            jpnDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jpnDaysLayout.setVerticalGroup(
            jpnDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Location:");

        javax.swing.GroupLayout jpnLocation1Layout = new javax.swing.GroupLayout(jpnLocation1);
        jpnLocation1.setLayout(jpnLocation1Layout);
        jpnLocation1Layout.setHorizontalGroup(
            jpnLocation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLocation1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(61, 61, 61)
                .addComponent(jtfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnLocation1Layout.setVerticalGroup(
            jpnLocation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLocation1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLocation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnOnsiteCourseLayout = new javax.swing.GroupLayout(jpnOnsiteCourse);
        jpnOnsiteCourse.setLayout(jpnOnsiteCourseLayout);
        jpnOnsiteCourseLayout.setHorizontalGroup(
            jpnOnsiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOnsiteCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOnsiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOnsiteCourseLayout.createSequentialGroup()
                        .addComponent(jpnLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jpnOnsiteCourseLayout.setVerticalGroup(
            jpnOnsiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOnsiteCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOnsiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnDays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnLocation1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnSearchLayout = new javax.swing.GroupLayout(jpnSearch);
        jpnSearch.setLayout(jpnSearchLayout);
        jpnSearchLayout.setHorizontalGroup(
            jpnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnOnlineCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnOnsiteCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSearchLayout.createSequentialGroup()
                        .addComponent(jbtnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnBack))
                    .addComponent(jbtnThem2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60))
        );
        jpnSearchLayout.setVerticalGroup(
            jpnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSearchLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnOnlineCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnOnsiteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jbtnThem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBack)
                    .addComponent(jbtnThem))
                .addContainerGap())
        );

        getContentPane().add(jpnSearch, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbOnlineOnsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOnlineOnsiteActionPerformed
        if(jcbOnlineOnsite.getSelectedItem() == "Online") {
            jpnOnlineCourse.setVisible(true);
            jpnOnsiteCourse.setVisible(false);
        } 
        else if (jcbOnlineOnsite.getSelectedItem() == "Onsite") {
            jpnOnlineCourse.setVisible(false);
            jpnOnsiteCourse.setVisible(true);
        }
        else {
            jpnOnlineCourse.setVisible(false);
            jpnOnsiteCourse.setVisible(false);
        }
    }//GEN-LAST:event_jcbOnlineOnsiteActionPerformed

     private void textFieldChange() {
        jtfTitle.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                textChanged();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                textChanged();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                textChanged();
            }

            private void textChanged() {
                String tf = jtfTitle.getText();
                String tfid = jtfCourseId.getText();
                if(tf.isEmpty()) {
                    jtfCourseId.setText("");
                }
                else if(tfid.isEmpty()){
                    try {
                        int id = couBLL.generateCourseID();
                        jtfCourseId.setText(id+"");
                    } catch (SQLException ex) {
                        Logger.getLogger(AddNewCourse1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }
    
    private void jtfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTitleActionPerformed

    }//GEN-LAST:event_jtfTitleActionPerformed

    private boolean checkBeforeAdd() {
        boolean check = true;
        if(jtfTitle.getText().isEmpty()) {
            check = false;
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên khóa học", "Lỗi", JOptionPane.WARNING_MESSAGE);
        }
        if (jcbOnlineOnsite.getSelectedIndex() < 0) {
            check = false;
            JOptionPane.showMessageDialog(null, "Vui lòng chọn loại khóa học", "Lỗi", JOptionPane.WARNING_MESSAGE);
        }
        if(jcbOnlineOnsite.getSelectedItem() == "Online"){
            if(jtfUrl.getText() == "") {
                check = false;
                JOptionPane.showMessageDialog(null, "Vui lòng nhập URL khóa học", "Lỗi", JOptionPane.WARNING_MESSAGE);
            }
        }
        if(jcbOnlineOnsite.getSelectedItem() == "Onsite"){
            if(jtfLocation.getText() == "") {
                check = false;
                JOptionPane.showMessageDialog(null, "Vui lòng nhập địa chỉ khóa học", "Lỗi", JOptionPane.WARNING_MESSAGE);
            }
            boolean checked = false;
            for (JPanel panel : checkBoxPanels) {
                JCheckBox checkBox = (JCheckBox) panel.getComponent(0);
                    if (checkBox.isSelected()) {
                        checked = true;
                    }
            }
            if(!checked) {
                check = false;
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ít nhất một ngày học", "Lỗi", JOptionPane.WARNING_MESSAGE);
            }
        }
        return check;
    }
    
    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        if(!checkBeforeAdd()) {
            return;
        }
        int CourseID = Integer.parseInt(jtfCourseId.getText());
        String name = jtfTitle.getText();
        int Credits = (int) jspCredits.getValue();
        Course c = new Course();
        c.setCourseId(CourseID);
        c.setCredits(Credits);
        c.setTitle(name);
        if(jcbOnlineOnsite.getSelectedItem() == "Online") {
            try {
                String url = jtfUrl.getText();
                OnlineCourse olc = new OnlineCourse();
                olc.setUrl(url);
                olc.setCourseId(CourseID);
                if(couBLL.addCourse(c) > 0 && olcBLL.addOnlineCourse(olc) > 0) {
                    JOptionPane.showConfirmDialog(null, "Thêm khóa online thành công!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddNewCourse1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else if (jcbOnlineOnsite.getSelectedItem() == "Onsite") {
            try {
                String location = jtfLocation.getText();
                String Days = "";
                for (JPanel panel : checkBoxPanels) {
                    JCheckBox checkBox = (JCheckBox) panel.getComponent(0);
                    
                    if (checkBox.isSelected()) {
                        if(checkBox.getText() == "Thu") {
                             Days += "H";
                        } 
                        else {
                            Days += checkBox.getText().charAt(0);
                        }
                        
                    }
                }
                Time time = Time.valueOf("00:00:00");
                time.setHours((int)hourSpinner.getValue());
                time.setMinutes((int)minuteSpinner.getValue());
                OnsiteCourse osc = new OnsiteCourse();
                osc.setCourseID(CourseID);
                osc.setDays(Days);
                osc.setLocation(location);
                osc.setTime(time);
                if(couBLL.addCourse(c) > 0 && oscBLL.addOnsiteCourse(osc) > 0) {
                    JOptionPane.showConfirmDialog(null, "Thêm khóa onsite thành công!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddNewCourse1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed

        dispose();
        try {
            cf.LastList = cf.lstcou = cf.cou.LoadCourses(1);
            cf.listCourse(cf.lstcou);
        } catch (SQLException ex) {
            Logger.getLogger(AddNewCourse1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnThem1;
    private javax.swing.JButton jbtnThem2;
    private javax.swing.JComboBox<String> jcbOnlineOnsite;
    private javax.swing.JPanel jpnDays;
    private javax.swing.JPanel jpnLocation1;
    private javax.swing.JPanel jpnOnlineCourse;
    private javax.swing.JPanel jpnOnsiteCourse;
    private javax.swing.JPanel jpnSearch;
    private javax.swing.JPanel jpnTime;
    private javax.swing.JSpinner jspCredits;
    private javax.swing.JTextField jtfCourseId;
    private javax.swing.JTextField jtfLocation;
    private javax.swing.JTextField jtfTitle;
    private javax.swing.JTextField jtfUrl;
    // End of variables declaration//GEN-END:variables
}
