
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DTO.CourseInstructor_DTO;
import BLL.ListCourseInstructor_BLL;
import DTO.Course_DTO;
import DTO.OfficeAssignment_DTO;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PhanCongGiangDay_GUI extends javax.swing.JFrame {
    Vector<CourseInstructor_DTO> listCInt=new Vector<CourseInstructor_DTO>();
     ListCourseInstructor_BLL couInsBLL =new ListCourseInstructor_BLL();
     OfficeAssignment_DTO offAsign=new OfficeAssignment_DTO();             // Giang vien duoc luu lai sau cac hanh dong
     Course_DTO courseDTO =new Course_DTO();                               //Khoa hoc duoc luu lai sau cac hanh dong
     CourseInstructor_DTO courseInsDTO ;
    DefaultTableModel model;
    int courseID;
    int PersonID;
    String courseName;
    String PersonName;
    String deparment;
    /**
     * Creates new form PhanCongGiangDay_GUI
     */
    public void setOffAsign(OfficeAssignment_DTO offAsign) {
        this.offAsign=offAsign;
    }

    public OfficeAssignment_DTO getOffAsign() {
        return offAsign;
    }
    public PhanCongGiangDay_GUI() throws SQLException {
        listCInt=couInsBLL.readCourseInstructor();
        initComponents();
        back_btn.setVisible(false);
                
        TableOutPut(listCInt);
    }
   public void TableOutPut(Vector<CourseInstructor_DTO> l){
        model= (DefaultTableModel) phancong_tb.getModel();
        model.setRowCount(0);
        for(CourseInstructor_DTO obj : l){
            
            courseID=obj.getCourse().getId();
            courseName=obj.getCourse().getTitle();
            PersonID=obj.getPerson().getId();
            PersonName=obj.getPerson().getLastName()+" "+obj.getPerson().getFirstName();
            deparment=obj.getCourse().getDepartment().getName();
            if (PersonID==-1)
            {
             Object[] row={courseID, courseName, "", PersonName, deparment};
            model.addRow(row);
            }
            else
            {
            Object[] row={courseID, courseName, PersonID, PersonName, deparment};
             model.addRow(row);
            }
            
           
                }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        title_lb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        department_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        course_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teacher_tf = new javax.swing.JTextField();
        btnOffice = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        search_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        search_select_cb = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        phancong_tb = new javax.swing.JTable();
        Ins_btn = new javax.swing.JRadioButton();
        notIns_btn = new javax.swing.JRadioButton();
        all_btn = new javax.swing.JRadioButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        buttonGroup1.add(Ins_btn);
        buttonGroup1.add(notIns_btn);
        buttonGroup1.add(all_btn);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phân công giảng dạy");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phân công giảng dạy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        title_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lb.setText("Thêm phân công giảng dạy");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Khoa    ");

        department_tf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        department_tf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        department_tf.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Khóa học    ");

        course_tf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        course_tf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        course_tf.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Giảng viên ");

        teacher_tf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teacher_tf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        teacher_tf.setEnabled(false);

        btnOffice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnOffice.setText("+");
        btnOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfficeActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back_btn.setText("Thoát ");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_btn.setText("Thêm mới");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        reset_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset_btn.setText("Xóa trắng");
        reset_btn.setMaximumSize(new java.awt.Dimension(116, 32));
        reset_btn.setMinimumSize(new java.awt.Dimension(116, 32));
        reset_btn.setPreferredSize(new java.awt.Dimension(116, 32));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(teacher_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOffice, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                            .addComponent(department_tf)
                            .addComponent(course_tf)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(department_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(course_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacher_tf)
                    .addComponent(btnOffice, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        search_tf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        search_tf.setToolTipText("");
        search_tf.setName(""); // NOI18N
        search_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_tfFocusLost(evt);
            }
        });
        search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_tfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Tìm kiếm :");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("+ Thêm phân công");
        jButton5.setActionCommand("");

        search_select_cb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        search_select_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khóa học", "Khóa học", "Mã giảng viên", "Giảng viên", "Khoa" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_select_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(search_select_cb)
        );

        phancong_tb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phancong_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khóa học", "Khóa học", "Mã giảng viên", "Giảng viên", "Khoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        phancong_tb.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        phancong_tb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        phancong_tb.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        phancong_tb.getTableHeader().setReorderingAllowed(false);
        phancong_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phancong_tbMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                phancong_tbMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(phancong_tb);

        Ins_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Ins_btn.setText("Khóa học đã phân công");
        Ins_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ins_btnActionPerformed(evt);
            }
        });

        notIns_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        notIns_btn.setText("Khóa học chưa phân công");
        notIns_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notIns_btnActionPerformed(evt);
            }
        });

        all_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        all_btn.setSelected(true);
        all_btn.setText("Tất cả");
        all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(all_btn)
                        .addGap(12, 12, 12)
                        .addComponent(notIns_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ins_btn)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ins_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(notIns_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(all_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_tfActionPerformed
        
            checkFilterCourseInstructor();
        
    }//GEN-LAST:event_search_tfActionPerformed

    private void search_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusGained
        
    }//GEN-LAST:event_search_tfFocusGained

    
    private void search_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusLost
        
    }//GEN-LAST:event_search_tfFocusLost

    private void btnOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfficeActionPerformed
        Search_Teacher_Dialog chonGiangVien = null;
       try {
           chonGiangVien = new Search_Teacher_Dialog(new javax.swing.JFrame(), true);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(Level.SEVERE, null, ex);
       }
        chonGiangVien.setVisible(true);
        
         
        
      if (chonGiangVien.getOfficeDTO()!=null)
      {
        offAsign=chonGiangVien.getOfficeDTO();
       
        teacher_tf.setText(offAsign.getName());
       
        
      }
        
        
        
    }//GEN-LAST:event_btnOfficeActionPerformed

    private void phancong_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phancong_tbMouseClicked
        
        int i =phancong_tb.getSelectedRow();
        courseInsDTO= new CourseInstructor_DTO();
        offAsign=null;
        if (i>=0)
        {
            
            if (phancong_tb.getValueAt(i, 3).toString().trim().equals(""))
            {
                int cID = Integer.parseInt(phancong_tb.getValueAt(i, 0).toString() );
             courseInsDTO=couInsBLL.getCourseById(cID);  
             department_tf.setText(courseInsDTO.getCourse().getDepartment().getName());
             course_tf.setText(courseInsDTO.getCourse().getTitle());
            teacher_tf.setText("");
           add_btn.setText("Thêm mới");
            reset_btn.setText("Xóa trắng");
             title_lb.setText("Thêm phân công giảng dạy");
             back_btn.setVisible(false);
             back_btn.enable(false);
             
            }
            else
            {
        int pID =Integer.parseInt(phancong_tb.getValueAt(i, 2).toString() );
        int cID = Integer.parseInt(phancong_tb.getValueAt(i, 0).toString() );
        courseInsDTO=couInsBLL.getCourseInstructorById(pID,cID);  
        department_tf.setText(courseInsDTO.getCourse().getDepartment().getName());
        course_tf.setText(courseInsDTO.getCourse().getTitle());
        teacher_tf.setText(courseInsDTO.getPerson().getName());
        add_btn.setText("Sửa phân công");
        reset_btn.setText("Xóa phân công");
        title_lb.setText("Sửa - Xóa phân công giảng dạy ");
        back_btn.setVisible(true);
        back_btn.enable(true);
         }
        }
    }//GEN-LAST:event_phancong_tbMouseClicked

    public void resetThem()
    {
        phancong_tb.clearSelection();
        department_tf.setText("");
        course_tf.setText("");
        teacher_tf.setText("");
        add_btn.setText("Thêm mới");
        reset_btn.setText("Xóa trắng");
        title_lb.setText("Thêm phân công giảng dạy");
        back_btn.setVisible(false);
        back_btn.enable(false);
        courseInsDTO=null;
    }
    public void checkFilterCourseInstructor()
    {
        String temp = search_tf.getText().toString().trim();
        resetThem();
        try {
            
            if(!temp.isEmpty() && search_select_cb.getSelectedIndex()==0){
                listCInt=new Vector<>(couInsBLL.All_Search("course.CourseID LIKE '%"+temp+"%'"));
                TableOutPut(listCInt);
            }else if(!temp.isEmpty() && search_select_cb.getSelectedIndex()==1){
                listCInt=new Vector<>(couInsBLL.All_Search("course.Title LIKE N'%"+temp+"%'"));
                TableOutPut(listCInt);
            }else if(!temp.isEmpty() && search_select_cb.getSelectedIndex()==2){
                listCInt=new Vector<>(couInsBLL.All_Search("person.PersonID LIKE '%"+temp+"%'"));
                TableOutPut(listCInt);
            }else if(!temp.isEmpty() && search_select_cb.getSelectedIndex()==3){
                listCInt=new Vector<>(couInsBLL.All_Search("CONCAT(person.Lastname, ' ', person.Firstname) LIKE N'%"+temp+"%'"));
                TableOutPut(listCInt);
            }else if(!temp.isEmpty() && search_select_cb.getSelectedIndex()==4){
                listCInt=new Vector<>(couInsBLL.All_Search("department.name LIKE N'%"+temp+"%'"));
                TableOutPut(listCInt);
            }else if(temp.isEmpty()){
                listCInt=new Vector<>(couInsBLL.readCourseInstructor());
                TableOutPut(listCInt);
            }
            
             if (all_btn.isSelected()==true)
            {
                 filter_CourseInstructor(couInsBLL.getCourseListInstructor());
            }
            else if (notIns_btn.isSelected()==true)
            {
                filter_CourseInstructor(couInsBLL.CourseNInstructor());
            }
            else
            {
                 filter_CourseInstructor(couInsBLL.CourseInstructor());
            }
        } catch (SQLException ex) {
            System.out.println("GUI"+ex);
        }
       
    }
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        resetThem();
    }//GEN-LAST:event_back_btnActionPerformed

    private void phancong_tbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phancong_tbMouseReleased
        phancong_tbMouseClicked(evt);
    }//GEN-LAST:event_phancong_tbMouseReleased

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
         if (reset_btn.getText().equals("Xóa trắng"))
      {
      phancong_tb.clearSelection();
      department_tf.setText("");
      course_tf.setText("");
      teacher_tf.setText("");
      }
      else
      {
           int i =phancong_tb.getSelectedRow();
          if (i>=0)
        {
          int pID =Integer.parseInt(phancong_tb.getValueAt(i, 2).toString() );
          int cID = Integer.parseInt(phancong_tb.getValueAt(i, 0).toString() );
          String result=couInsBLL.deleteCourseInstructor(pID,cID);
          listCInt=couInsBLL.readCourseInstructor();
          resetThem();
          checkFilterCourseInstructor();
          JOptionPane.showMessageDialog(rootPane,result );
        }
          
      }
    }//GEN-LAST:event_reset_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
       if (add_btn.getText().equals("Thêm mới"))
       {
           if (course_tf.getText().trim().equals(""))
           {
               JOptionPane.showMessageDialog(rootPane,"Vui lòng chọn khóa học khả dụng");
               
           }
           else if (teacher_tf.getText().trim().equals(""))
           {
               JOptionPane.showMessageDialog(rootPane,"Vui lòng chọn giảng viên khả dụng");
           }
           else
           {
               int i =phancong_tb.getSelectedRow();
          if (i>=0)
        {
            
            
          int pID =offAsign.getId();                        
          int cID = courseInsDTO.getCourse().getId();
               
          String result=couInsBLL.addCourseInstructor(pID, cID);
           JOptionPane.showMessageDialog(rootPane,result);
               resetThem();
               listCInt=couInsBLL.readCourseInstructor();
                checkFilterCourseInstructor();
           
               
           
            }
           }
       }
       else
       {
           int i =phancong_tb.getSelectedRow();
          if (i>=0)
        {
          int pID1=courseInsDTO.getPerson().getId();
          
              if (offAsign!=null)
              {
          int pID2 =offAsign.getId(); 
          if (pID1!=pID2)
          {
          int cID = courseInsDTO.getCourse().getId();
          String result=couInsBLL.updateCourseInstructor(pID1, pID2, cID);
           JOptionPane.showMessageDialog(rootPane,result);
               resetThem();
               listCInt=couInsBLL.readCourseInstructor();
               checkFilterCourseInstructor();
          }
              }
          
       }
       }
    }//GEN-LAST:event_add_btnActionPerformed

    private void notIns_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notIns_btnActionPerformed
       
       filter_CourseInstructor(couInsBLL.CourseNInstructor());
    }//GEN-LAST:event_notIns_btnActionPerformed

    private void Ins_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ins_btnActionPerformed
        
      
        filter_CourseInstructor(couInsBLL.CourseInstructor());
    }//GEN-LAST:event_Ins_btnActionPerformed

    private void all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_btnActionPerformed
     
       filter_CourseInstructor(couInsBLL.getCourseListInstructor());
    }//GEN-LAST:event_all_btnActionPerformed

    public void filter_CourseInstructor(Vector<CourseInstructor_DTO> list)
    {
       TableOutPut(list);
       resetThem();
    }
//    public void resetAll()
//    {
//         resetThem();
//         search_tf.setText("Nhập thông tin tìm kiếm");
//         all_btn.setSelected(true);
//                 
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhanCongGiangDay_GUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PhanCongGiangDay_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ins_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JRadioButton all_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton btnOffice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField course_tf;
    private javax.swing.JTextField department_tf;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton notIns_btn;
    private javax.swing.JTable phancong_tb;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox<String> search_select_cb;
    private javax.swing.JTextField search_tf;
    private javax.swing.JTextField teacher_tf;
    private javax.swing.JLabel title_lb;
    // End of variables declaration//GEN-END:variables
}
