/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.OfficeAssignment_BLL;
import BLL.ListCourseInstructor_BLL;
import DTO.CourseInstructor_DTO;
import DTO.OfficeAssignment_DTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Search_Teacher_Dialog extends javax.swing.JDialog {
     Vector<OfficeAssignment_DTO> listOffAssign=new Vector<OfficeAssignment_DTO>();
     OfficeAssignment_BLL offAssignBLL =new OfficeAssignment_BLL();
     OfficeAssignment_DTO officeDTO ;
     Vector<CourseInstructor_DTO> listcourseIns=new Vector<CourseInstructor_DTO>();
     ListCourseInstructor_BLL courseInsBLL =new ListCourseInstructor_BLL();
     CourseInstructor_DTO courseInsDTO ;
    /**
     * Creates new form Search_Teacher_Dialog
     */
    public Search_Teacher_Dialog(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, SQLException {
        super(parent, modal); 
        listOffAssign=offAssignBLL.readOfficeAssignment();
        initComponents();
        checkCourse(0);
    }

    public OfficeAssignment_DTO getOfficeDTO() {
        return officeDTO;
    }
    public void locChuaPhanCong(){
        listOffAssign=offAssignBLL.getOfficeList();
        Vector<OfficeAssignment_DTO> list=new Vector<OfficeAssignment_DTO>();
       for (OfficeAssignment_DTO x:listOffAssign)
       {
            CourseInstructor_DTO temp=courseInsBLL.getPersonById(x.getId());
            if(temp==null){
                list.add(x);
            }
        }
        loadOfficeAssignment(list);
    }
    public void locDaPhanCong(){
        listOffAssign=offAssignBLL.getOfficeList();
        Vector<OfficeAssignment_DTO> list=new Vector<OfficeAssignment_DTO>();
        for (OfficeAssignment_DTO x:listOffAssign)
       {
            CourseInstructor_DTO temp=courseInsBLL.getPersonById(x.getId());
            if(temp!=null){
                list.add(x);
            }
        }
        loadOfficeAssignment(list);
    }
    public void Search() throws SQLException{
        String temp = jTextField1.getText().toString();
        try {
            if(!temp.isEmpty() && jComboBox1.getSelectedIndex()==0){
                listOffAssign=new Vector<>(offAssignBLL.All_Search("person.PersonID LIKE '%"+temp+"%'"));
            }else if(!temp.isEmpty() && jComboBox1.getSelectedIndex()==1){
                listOffAssign=new Vector<>(offAssignBLL.All_Search("CONCAT(person.Lastname, ' ', person.Firstname) LIKE N'%"+temp+"%'"));
            }else if(temp.isEmpty()){
                listOffAssign=new Vector<>(offAssignBLL.readOfficeAssignment());
            }
            
        } catch (SQLException ex) {
            System.out.println("GUI"+ex);
        }
    }
    public void checkCourse(int buttonstate){
        if(buttonstate==0){
            locChuaPhanCong();
        }else if(buttonstate==1){
            locDaPhanCong();
        }
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_giangvien = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chọn giảng viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Tìm kiếm :");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tb_giangvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_giangvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã giảng viên", "Tên giảng viên", "Liên hệ"
            }
        )
        {

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

        }
    );
    tb_giangvien.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    tb_giangvien.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent evt) {

            selectOfficeAssign();

        }
        public void mouseReleased(MouseEvent evt) {

            selectOfficeAssign();

        }
    });

    tb_giangvien.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tb_giangvien);

    jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên" }));

    jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jRadioButton1.setSelected(true);
    jRadioButton1.setText("Chưa phân công");
    jRadioButton1.setToolTipText("");
    jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jRadioButton1ItemStateChanged(evt);
        }
    });

    jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jRadioButton2.setText("Đã phân công");
    jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jRadioButton2ItemStateChanged(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox1, 0, 73, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButton1)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jComboBox1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
         try {
             Search();
         } catch (SQLException ex) {
             Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(Level.SEVERE, null, ex);
         }
        if(jRadioButton1.isSelected()){
            checkCourse(0);
        }else if(jRadioButton2.isSelected()){
            checkCourse(1);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        if(evt.getStateChange()==1){
            if(jRadioButton1.isSelected()){
                if(jTextField1.getText().toString().isEmpty()){
                    listOffAssign=offAssignBLL.readOfficeAssignment();
                    checkCourse(0);
                }else{
                    try {
                        Search();
                        checkCourse(0);
                    } catch (SQLException ex) {
                        Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        if(evt.getStateChange()==1){
            if(jRadioButton2.isSelected()){
                if(jTextField1.getText().toString().isEmpty()){
                    listOffAssign=offAssignBLL.readOfficeAssignment();
                    checkCourse(1);
                }else{
                    try {
                        Search();
                        checkCourse(1);
                    } catch (SQLException ex) {
                        Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_jRadioButton2ItemStateChanged
 
    public void loadOfficeAssignment(Vector<OfficeAssignment_DTO> list)
    {
        DefaultTableModel model = (DefaultTableModel) tb_giangvien.getModel();
        model.setRowCount(0);
        if ( list!=null)
        for (int i = 0; i <  list.size(); i++) {
            model.addRow(new Object[]{list.get(i).getId(), list.get(i).getName(), list.get(i).getLocation()});
        }
    }
 public void selectOfficeAssign()
 {
     
     int i = tb_giangvien.getSelectedRow();
     officeDTO= new OfficeAssignment_DTO();
     if (i>=0)
     {
         
         if (jRadioButton1.isSelected())
     {
    dispose();
     officeDTO=offAssignBLL.getOfficeAssignmentById(Integer.parseInt(tb_giangvien.getValueAt(i, 0).toString()));
     JOptionPane.showMessageDialog(rootPane, "Chọn giảng viên thành công ");
     }
     else 
     {
         officeDTO=null;
         JOptionPane.showMessageDialog(rootPane, "Giảng viên này đã được phân công ! \nVui lòng chọn giảng viên ở tùy chọn chưa được phân công !");
     }
         
      
         
         
     }
     
             
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Search_Teacher_Dialog(new javax.swing.JFrame(), true).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Search_Teacher_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tb_giangvien;
    // End of variables declaration//GEN-END:variables
}
